import {
  Backpack,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Cake,
  Camera,
  Car,
  CircleHelp,
  Coffee,
  CreditCard,
  Crown,
  Dumbbell,
  Film,
  Flag,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  House,
  IceCreamCone,
  Landmark,
  Laptop,
  Leaf,
  Music,
  Palette,
  PawPrint,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Popcorn,
  Repeat,
  Scissors,
  Shapes,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Store,
  Ticket,
  TrainFront,
  Trophy,
  Tv,
  Undo2,
  Utensils,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Category/account icons by name, so the name can be stored in the DB.
 * `PICKABLE_ICONS` is what the custom-category picker offers.
 */
export const ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  bus: Bus,
  'shopping-bag': ShoppingBag,
  popcorn: Popcorn,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  repeat: Repeat,
  gift: Gift,
  sparkles: Sparkles,
  shapes: Shapes,
  'hand-coins': HandCoins,
  briefcase: Briefcase,
  undo: Undo2,
  landmark: Landmark,
  smartphone: Smartphone,
  banknote: Banknote,
  'credit-card': CreditCard,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  'circle-help': CircleHelp,
  coffee: Coffee,
  dumbbell: Dumbbell,
  flag: Flag,
  heart: Heart,
  laptop: Laptop,
  gamepad: Gamepad2,
  music: Music,
  plane: Plane,
  train: TrainFront,
  car: Car,
  bike: Bike,
  book: BookOpen,
  shirt: Shirt,
  scissors: Scissors,
  pizza: Pizza,
  beer: Beer,
  cake: Cake,
  film: Film,
  wifi: Wifi,
  house: House,
  paw: PawPrint,
  palette: Palette,
  camera: Camera,
  ticket: Ticket,
  gem: Gem,
  fuel: Fuel,
  trophy: Trophy,
  zap: Zap,
  leaf: Leaf,
  pill: Pill,
  tv: Tv,
  headphones: Headphones,
  'ice-cream': IceCreamCone,
  backpack: Backpack,
  store: Store,
  crown: Crown,
}

export const PICKABLE_ICONS = [
  'utensils', 'coffee', 'pizza', 'ice-cream', 'beer', 'cake',
  'bus', 'train', 'car', 'bike', 'fuel', 'plane',
  'shopping-bag', 'shirt', 'gem', 'store', 'gift', 'heart',
  'popcorn', 'film', 'ticket', 'gamepad', 'music', 'headphones',
  'graduation-cap', 'book', 'backpack', 'laptop', 'wifi', 'tv',
  'heart-pulse', 'pill', 'dumbbell', 'scissors', 'sparkles', 'palette',
  'flag', 'trophy', 'crown', 'camera', 'paw', 'leaf',
  'house', 'zap', 'repeat', 'briefcase', 'hand-coins', 'shapes',
]

export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Shapes
}

